PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

TARGET := example_debug \
          example_log

SRC_C_example_debug := example_debug.c
SRC_C_example_log   := example_log.c

REQUIRES_LIBS := l4re_c l4re_c-util

include $(L4DIR)/mk/prog.mk
